# Generated by Django 6.0.6 on 2026-06-07 06:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_view_count_postview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='postview',
            name='unique_post_view_ip',
        ),
        migrations.RenameIndex(
            model_name='postview',
            new_name='posts_postv_post_id_f72761_idx',
            old_name='posts_postv_post_id_6f8b0d_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='YouTube, Vimeo, Rutube, VK Video или Дзен — показывается при доступе к публикации.', max_length=500, verbose_name='Ссылка на видео'),
        ),
        migrations.AddConstraint(
            model_name='postview',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('ip_hash', ''), _negated=True)), fields=('post', 'ip_hash'), name='unique_post_view_ip'),
        ),
    ]
